---
apiVersion: v1
kind: Service
metadata:
  name: flask-ip-reverse-app
spec:
  type: LoadBalancer
  selector:
    app: flask-ip-reverse-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80