apiVersion: v1
kind: Service
metadata:
  name: flask-ip-reverse-app
  namespace: revip
spec:
  selector:
    app: flask-ip-reverse-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer #to expose
